name: Ember test audit
on: pull_request

jobs:
  time-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd ui && yarn --frozen-lockfile
      - name: Audit tests
        shell: bash
        working-directory: ui
        run: "echo \"::add-path::./node_modules/.bin\""
      - run: echo $PATH
      - run: ember test
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: master-audit
          path: master-audit.txt
  time-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd ui && yarn --frozen-lockfile
      - name: Audit tests
        shell: bash
        working-directory: ui
        run: "echo \"::add-path::./node_modules/.bin\""
      - run: echo $PATH
      - run: ember test
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: pr-audit
          path: pr-audit.txt
  compare:
    needs: [time-master, time-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: master-audit
      - uses: actions/download-artifact@v2
        with:
          name: pr-audit
      - name: Print results
        shell: bash
        run: node .github/actions/ember-test-audit-diff/index.js master-audit.txt pr-audit.txt
